// Generated by ts-to-zod
import { z } from "zod";
import { AppPermission, AppRequestedLocation, AppExpandLevel, AppLocation, AppFormFieldType, AppFormFieldSubType } from "./apps";

export const appPermissionSchema = z.enum(AppPermission);

export const appRequestedLocationSchema = z.enum(AppRequestedLocation);

export const appManifestSchema = z.object({
    app_id: z.string(),
    version: z.string().optional(),
    homepage_url: z.string().optional(),
    icon: z.string().optional(),
    display_name: z.string(),
    description: z.string().optional(),
    requested_permissions: z.array(appPermissionSchema).optional(),
    requested_locations: z.array(appRequestedLocationSchema).optional()
});

export const appExpandLevelSchema = z.enum(AppExpandLevel);

export const appContextPropsSchema = z.record(z.string(), z.string());

export const appContextSchema = z.object({
    app_id: z.string(),
    location: z.string().optional(),
    acting_user_id: z.string().optional(),
    user_id: z.string().optional(),
    channel_id: z.string().optional(),
    team_id: z.string().optional(),
    post_id: z.string().optional(),
    root_id: z.string().optional(),
    props: appContextPropsSchema.optional(),
    user_agent: z.string().optional(),
    track_as_submit: z.boolean().optional()
});

export const appExpandSchema = z.object({
    app: appExpandLevelSchema.optional(),
    acting_user: appExpandLevelSchema.optional(),
    acting_user_access_token: appExpandLevelSchema.optional(),
    channel: appExpandLevelSchema.optional(),
    config: appExpandLevelSchema.optional(),
    mentioned: appExpandLevelSchema.optional(),
    parent_post: appExpandLevelSchema.optional(),
    post: appExpandLevelSchema.optional(),
    root_post: appExpandLevelSchema.optional(),
    team: appExpandLevelSchema.optional(),
    user: appExpandLevelSchema.optional(),
    locale: appExpandLevelSchema.optional()
});

export const appCallValuesSchema = z.record(z.string(), z.unknown());

export const appCallMetadataForClientSchema = z.object({
    bot_user_id: z.string(),
    bot_username: z.string()
});

export const appCallSchema = z.object({
    path: z.string(),
    expand: appExpandSchema.optional(),
    state: z.unknown().optional()
});

export const appCallRequestSchema = appCallSchema.extend({
    context: appContextSchema,
    values: appCallValuesSchema.optional(),
    raw_command: z.string().optional(),
    selected_field: z.string().optional(),
    query: z.string().optional()
});

export const appLocationSchema = z.enum(AppLocation);

export const appFormSelectOptionSchema = z.object({
    label: z.string(),
    value: z.string(),
    icon_data: z.string().optional()
});

export const appFormLookupResponseSchema = z.object({
    items: z.array(appFormSelectOptionSchema)
});

export const appFormResponseDataSchema = z.object({
    errors: z.record(z.string(), z.string()).optional()
});

export const appFormFieldTypeSchema = z.enum(AppFormFieldType);

export const appFormFieldSubTypeSchema = z.enum(AppFormFieldSubType);

const multiselectableSchema = z.object({
    multiselect: z.boolean().optional().describe("Whether a select field allows multiple values to be selected.")
});

const refreshableSchema = z.object({
    refresh: z.boolean().optional().describe("Allows the form to be refreshed when the value of the field has changed.")
});

export const appFormFieldOptionSchema = z.object({
    label: z.string().optional().describe("User-facing string.\nDefaults to value and must be unique on this field."),
    value: z.string().describe("Machine-facing value. Must be unique on this field."),
    icon_data: z.string().optional().describe("Either a fully-qualified URL, or a path for an app's static asset")
});

export const appFormTextFieldSchema = z.object({
    type: z.literal(AppFormFieldType.TEXT),
    subtype: appFormFieldSubTypeSchema.optional().describe("The subtype of text field that will be shown."),
    min_length: z.number().optional().describe("The minimum length of text field input."),
    max_length: z.number().optional().describe("The maximum length of text field input.")
});

const productScopeSchema = z.any();

export const appFormValuesSchema = z.record(z.string(), z.union([z.string(), appFormSelectOptionSchema, z.boolean()]).nullable());
