// Generated by ts-to-zod
import { z } from "zod";

export const botSchema = z.object({
    user_id: z.string(),
    username: z.string(),
    display_name: z.string().optional(),
    description: z.string().optional(),
    owner_id: z.string(),
    create_at: z.number(),
    update_at: z.number(),
    delete_at: z.number()
});

export const botPatchSchema = z.object({
    username: z.string(),
    display_name: z.string(),
    description: z.string()
});
