// Generated by ts-to-zod
import { z } from "zod";
import { ChannelType, ChannelNotify, ChannelNotifyDesktopSound, ChannelCategoryType, ChannelCategorySorting, ChannelBookmarkType } from "./channels";

export const channelTypeSchema = z.enum(ChannelType);

export const channelNotifySchema = z.enum(ChannelNotify);

export const channelNotifyDesktopSoundSchema = z.enum(ChannelNotifyDesktopSound);

export const channelSchema = z.object({
    id: z.string(),
    create_at: z.number(),
    update_at: z.number(),
    delete_at: z.number(),
    team_id: z.string(),
    type: channelTypeSchema,
    display_name: z.string(),
    name: z.string(),
    header: z.string(),
    purpose: z.string(),
    last_post_at: z.number(),
    total_msg_count: z.number(),
    extra_update_at: z.number(),
    creator_id: z.string(),
    scheme_id: z.string().optional().nullable(),
    props: z.record(z.string(), z.unknown()).optional().nullable(),
    group_constrained: z.boolean().optional().nullable(),
    shared: z.boolean().optional().nullable(),
    total_msg_count_root: z.number(),
    policy_id: z.string().nullable(),
    last_root_post_at: z.number()
}).describe("Channel main object\n===============================================");

export const channelCategoryTypeSchema = z.enum(ChannelCategoryType);

export const channelCategorySortingSchema = z.enum(ChannelCategorySorting);

export const channelCategorySchema = z.object({
    id: z.string(),
    user_id: z.string(),
    team_id: z.string(),
    type: channelCategoryTypeSchema,
    display_name: z.string(),
    sorting: channelCategorySortingSchema,
    channel_ids: z.array(z.string()),
    muted: z.boolean(),
    collapsed: z.boolean()
});

export const orderedChannelCategoriesSchema = z.object({
    categories: z.array(channelCategorySchema),
    order: z.array(z.string())
});

export const channelBookmarkTypeSchema = z.enum(ChannelBookmarkType);

export const channelBookmarkCreateLinkSchema = z.object({
    type: z.literal(ChannelBookmarkType.LINK),
    link_url: z.string()
});

export const channelBookmarkCreateFileSchema = z.object({
    type: z.literal(ChannelBookmarkType.FILE),
    file_id: z.string()
});

export const channelBookmarkCreateBaseSchema = z.object({
    display_name: z.string(),
    image_url: z.string().optional(),
    emoji: z.string().optional()
});

export const channelBookmarkCreateSchema = channelBookmarkCreateBaseSchema.and(z.union([channelBookmarkCreateLinkSchema, channelBookmarkCreateFileSchema]));

export const channelBookmarkPatchSchema = z.object({
    file_id: z.string().optional(),
    display_name: z.string().optional(),
    sort_order: z.number().optional(),
    link_url: z.string().optional(),
    image_url: z.string().optional(),
    emoji: z.string().optional()
});

export const channelMessageCountSchema = z.object({
    total: z.number(),
    root: z.number()
});

export const channelModerationSchema = z.object({
    name: z.string(),
    roles: z.object({
        guests: z.object({
            value: z.boolean(),
            enabled: z.boolean()
        }).optional(),
        members: z.object({
            value: z.boolean(),
            enabled: z.boolean()
        }),
        admins: z.object({
            value: z.boolean(),
            enabled: z.boolean()
        })
    })
});

export const channelModerationPatchSchema = z.object({
    name: z.string(),
    roles: z.object({
        guests: z.boolean().optional(),
        members: z.boolean().optional()
    })
});

export const channelWithTeamDataSchema = channelSchema.extend({
    team_display_name: z.string(),
    team_name: z.string(),
    team_update_at: z.number()
});

export const channelsWithTotalCountSchema = z.object({
    channels: z.array(channelWithTeamDataSchema),
    total_count: z.number()
});

export const channelMemberCountByGroupSchema = z.object({
    group_id: z.string(),
    channel_member_count: z.number(),
    channel_member_timezones_count: z.number()
});

export const channelMemberCountsByGroupSchema = z.record(z.string(), channelMemberCountByGroupSchema);

export const channelViewResponseSchema = z.object({
    status: z.string(),
    last_viewed_at_times: z.record(z.string(), z.number())
});

export const channelStatsSchema = z.object({
    channel_id: z.string(),
    member_count: z.number(),
    guest_count: z.number(),
    pinnedpost_count: z.number(),
    files_count: z.number()
});

export const channelNotifyPropsResponseSchema = z.object({
    desktop_threads: channelNotifySchema,
    desktop: channelNotifySchema,
    desktop_sound: z.union([z.literal("on"), z.literal("off")]),
    desktop_notification_sound: channelNotifyDesktopSoundSchema.optional(),
    email: channelNotifySchema,
    mark_unread: channelNotifySchema,
    push: channelNotifySchema,
    push_threads: channelNotifySchema,
    ignore_channel_mentions: z.union([z.literal("default"), z.literal("off"), z.literal("on")]),
    channel_auto_follow_threads: z.union([z.literal("off"), z.literal("on")])
});

export const channelUnreadResponseSchema = z.object({
    channel_id: z.string(),
    user_id: z.string(),
    team_id: z.string(),
    msg_count: z.number(),
    msg_count_root: z.number(),
    mention_count: z.number(),
    urgent_mention_count: z.number(),
    mention_count_root: z.number(),
    last_viewed_at: z.number(),
    deltaMsgs: z.number()
});

const fileInfoSchema = z.any();

export const serverChannelSchema = channelSchema.extend({
    total_msg_count: z.number(),
    total_msg_count_root: z.number()
});

export const channelBookmarkSchema = z.object({
    id: z.string(),
    create_at: z.number(),
    update_at: z.number(),
    delete_at: z.number(),
    channel_id: z.string(),
    owner_id: z.string(),
    file_id: z.string().optional(),
    file: fileInfoSchema.optional(),
    display_name: z.string(),
    sort_order: z.number(),
    link_url: z.string().optional(),
    image_url: z.string().optional(),
    emoji: z.string().optional(),
    type: channelBookmarkTypeSchema,
    original_id: z.string().optional(),
    parent_id: z.string().optional()
});

export const channelBookmarkWithFileInfoSchema = channelBookmarkSchema.extend({
    file: fileInfoSchema.optional()
});

export const channelMembershipSchema = z.object({
    channel_id: z.string(),
    user_id: z.string(),
    roles: z.string(),
    last_viewed_at: z.number(),
    msg_count: z.number(),
    msg_count_root: z.number(),
    mention_count: z.number(),
    mention_count_root: z.number(),
    urgent_mention_count: z.number(),
    notify_props: channelNotifyPropsResponseSchema.partial(),
    last_update_at: z.number(),
    scheme_user: z.boolean(),
    scheme_admin: z.boolean(),
    post_root_id: z.string().optional()
});
