// Generated by ts-to-zod
import { z } from "zod";

export const statusOkSchema = z.object({
    status: z.literal("OK")
});

export const systemSettingSchema = z.object({
    name: z.string(),
    value: z.string()
});
