// Generated by ts-to-zod
import { z } from "zod";
import { EmojiCategory } from "./emojis";

export const emojiCategorySchema = z.enum(EmojiCategory);

export const customEmojiSchema = z.object({
    id: z.string(),
    name: z.string(),
    category: z.literal(EmojiCategory.CUSTOM),
    create_at: z.number(),
    update_at: z.number(),
    delete_at: z.number(),
    creator_id: z.string()
});

export const recentEmojiDataSchema = z.object({
    name: z.string(),
    usageCount: z.number()
});

export const systemEmojiVariationSchema = z.object({
    unified: z.string(),
    non_qualified: z.null(),
    image: z.string(),
    sheet_x: z.number(),
    sheet_y: z.number(),
    added_in: z.string(),
    has_img_apple: z.boolean(),
    has_img_google: z.boolean(),
    has_img_twitter: z.boolean(),
    has_img_facebook: z.boolean()
});

export const systemEmojiSchema = z.object({
    name: z.string(),
    category: emojiCategorySchema,
    image: z.string(),
    short_name: z.string(),
    short_names: z.array(z.string()),
    batch: z.number(),
    skins: z.array(z.string()).optional(),
    skin_variations: z.record(z.string(), systemEmojiVariationSchema).optional(),
    unified: z.string()
});

export const emojiSchema = z.union([systemEmojiSchema, customEmojiSchema]);
