// Generated by ts-to-zod
import { z } from "zod";

export const filesUsageResponseSchema = z.object({
    bytes: z.number()
});

export const fileInfoSchema = z.object({
    id: z.string(),
    user_id: z.string(),
    create_at: z.number(),
    update_at: z.number(),
    delete_at: z.number(),
    name: z.string(),
    extension: z.string(),
    size: z.number(),
    mime_type: z.string(),
    width: z.number(),
    height: z.number(),
    has_preview_image: z.boolean(),
    clientId: z.string(),
    post_id: z.string().optional(),
    mini_preview: z.string().optional(),
    archived: z.boolean(),
    link: z.string().optional()
}).describe("Main file info object");

export const fileSearchResultItemSchema = fileInfoSchema.extend({
    channel_id: z.string()
});

export const uploadSessionSchema = z.object({
    id: z.string(),
    type: z.string(),
    create_at: z.number(),
    path: z.string(),
    file_size: z.number(),
    file_offset: z.number()
});

export const fileUploadResponseSchema = z.object({
    file_infos: z.array(fileInfoSchema),
    client_ids: z.array(z.string())
});
