// Generated by ts-to-zod
import { z } from "zod";

export const openGraphMetadataImageSchema = z.object({
    secure_url: z.string().optional(),
    url: z.string(),
    type: z.string().optional(),
    height: z.number().optional(),
    width: z.number().optional()
});

export const openGraphMetadataSchema = z.object({
    type: z.string().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    site_name: z.string().optional(),
    url: z.string().optional(),
    images: z.array(openGraphMetadataImageSchema)
});
