// Generated by ts-to-zod
import { z } from "zod";

const messageDescriptorSchema = z.object({
    id: z.string(),
    defaultMessage: z.string()
});

export const pluginManifestServerSchema = z.object({
    executables: z.object({
        "linux-amd64": z.string().optional(),
        "darwin-amd64": z.string().optional(),
        "windows-amd64": z.string().optional()
    }).optional(),
    executable: z.string()
});

export const pluginManifestWebappSchema = z.object({
    bundle_path: z.string()
});

export const pluginSettingOptionSchema = z.object({
    display_name: z.string(),
    value: z.string()
});

export const pluginStatusSchema = z.object({
    plugin_id: z.string(),
    cluster_id: z.string(),
    plugin_path: z.string(),
    state: z.number(),
    name: z.string(),
    description: z.string(),
    version: z.string()
});

const pluginInstanceSchema = z.object({
    cluster_id: z.string(),
    version: z.string(),
    state: z.number()
});

export const pluginStatusReduxSchema = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    version: z.string(),
    active: z.boolean(),
    state: z.number(),
    error: z.string().optional(),
    instances: z.array(pluginInstanceSchema)
});

export const clientPluginManifestSchema = z.object({
    id: z.string(),
    min_server_version: z.string().optional(),
    version: z.string(),
    webapp: z.object({
        bundle_path: z.string()
    })
});

export const pluginSettingSchema = z.object({
    key: z.string(),
    display_name: z.string(),
    type: z.string(),
    help_text: z.union([z.string(), messageDescriptorSchema]),
    regenerate_help_text: z.string().optional(),
    placeholder: z.string(),
    default: z.unknown(),
    options: z.array(pluginSettingOptionSchema).optional(),
    hosting: z.union([z.literal("on-prem"), z.literal("cloud")]).optional()
});

export const pluginSettingsSchemaSchema = z.object({
    header: z.string(),
    footer: z.string(),
    settings: z.array(pluginSettingSchema)
});

export const pluginManifestSchema = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string().optional(),
    homepage_url: z.string().optional(),
    support_url: z.string().optional(),
    release_notes_url: z.string().optional(),
    icon_path: z.string().optional(),
    version: z.string(),
    min_server_version: z.string().optional(),
    translate: z.boolean().optional(),
    server: pluginManifestServerSchema.optional(),
    backend: pluginManifestServerSchema.optional(),
    webapp: pluginManifestWebappSchema.optional(),
    settings_schema: pluginSettingsSchemaSchema.optional(),
    props: z.record(z.string(), z.unknown()).and(z.object({
        enterprise: z.boolean(),
        experimental: z.boolean()
    })).optional()
});

export const pluginsResponseSchema = z.object({
    active: z.array(pluginManifestSchema),
    inactive: z.array(pluginManifestSchema)
});

export const pluginsGetResponseSchema = z.object({
    active: z.array(pluginManifestSchema),
    inactive: z.array(pluginManifestSchema)
});

export const pluginReduxSchema = pluginManifestSchema.and(z.object({
    active: z.boolean()
}));
