// Generated by ts-to-zod
import { z } from "zod";
import { type Post, type PostMetadata, type PostEmbed, type PostPreviewMetadata, type PostListResponse, type PaginatedPostListResponse, type PostSearchResponse, PostType, PostState, PostPriority, PostEmbedType, PostAttachmentColor, PostActionStyle, PostActionType, PostActionDataSource, PostNotificationStatus } from "./posts";

export const postTypeSchema = z.enum(PostType);

export const postStateSchema = z.enum(PostState);

export const postPrioritySchema = z.enum(PostPriority);

export const postEmbedTypeSchema = z.enum(PostEmbedType);

export const postPriorityMetadataSchema = z.object({
    priority: postPrioritySchema,
    requested_ack: z.boolean().optional(),
    persistent_notifications: z.boolean().optional()
});

export const postImageSchema = z.object({
    format: z.string(),
    frameCount: z.number(),
    height: z.number(),
    width: z.number()
});

export const postAcknowledgementSchema = z.object({
    post_id: z.string(),
    user_id: z.string(),
    acknowledged_at: z.number()
});

export const postAttachmentColorSchema = z.enum(PostAttachmentColor);

export const postAttachmentFieldSchema = z.object({
    title: z.string(),
    value: z.unknown(),
    short: z.boolean()
});

export const postActionStyleSchema = z.enum(PostActionStyle);

export const postActionTypeSchema = z.enum(PostActionType);

export const postActionDataSourceSchema = z.enum(PostActionDataSource);

export const postActionOptionSchema = z.object({
    text: z.string(),
    value: z.string()
});

export const postContextPropsSchema = z.record(z.string(), z.string()).describe("Posts context\n===============================================");

export const postContextSchema = z.record(z.string(), z.unknown()).and(z.object({
    app_id: z.string().optional(),
    location: z.string().optional(),
    acting_user_id: z.string().optional(),
    user_id: z.string().optional(),
    channel_id: z.string().optional(),
    team_id: z.string().optional(),
    post_id: z.string().optional(),
    root_id: z.string().optional(),
    props: postContextPropsSchema.optional(),
    user_agent: z.string().optional(),
    track_as_submit: z.boolean().optional(),
    acting_user: z.object({
        id: z.string()
    }).optional()
}));

export const postNotificationStatusSchema = z.enum(PostNotificationStatus);

export const postsUsageResponseSchema = z.object({
    count: z.number()
});

export const postNotificationResponseSchema = z.object({
    status: postNotificationStatusSchema,
    reason: z.string().optional(),
    data: z.string().optional()
});

export const postAnalyticsSchema = z.object({
    channel_id: z.string(),
    post_id: z.string(),
    user_actual_id: z.string(),
    root_id: z.string(),
    priority: postPrioritySchema.optional(),
    requested_ack: z.union([z.boolean(), z.undefined()]).optional(),
    persistent_notifications: z.union([z.boolean(), z.undefined()]).optional()
});

export const postOrderBlockSchema = z.object({
    order: z.array(z.string()),
    recent: z.boolean().optional(),
    oldest: z.boolean().optional()
});

export const messageHistorySchema = z.object({
    messages: z.array(z.string()),
    index: z.object({
        post: z.number(),
        comment: z.number()
    })
});

export const postActivityEntrySchema = z.object({
    postType: postTypeSchema,
    actorId: z.array(z.string()),
    userIds: z.array(z.string()),
    usernames: z.array(z.string())
});

export const postInfoSchema = z.object({
    channel_id: z.string(),
    channel_type: z.string(),
    channel_display_name: z.string(),
    has_joined_channel: z.boolean(),
    team_id: z.string(),
    team_type: z.string(),
    team_display_name: z.string(),
    has_joined_team: z.boolean()
});

const openGraphMetadataSchema = z.any();

const customEmojiSchema = z.any();

const fileInfoSchema = z.any();

const reactionSchema = z.any();

export const postActionIntegrationSchema = z.object({
    url: z.string(),
    context: postContextSchema.optional()
});

export const postActionSchema = z.object({
    id: z.string(),
    name: z.string(),
    integration: postActionIntegrationSchema,
    type: postActionTypeSchema,
    options: z.array(postActionOptionSchema).optional(),
    style: postActionStyleSchema.optional(),
    data_source: postActionDataSourceSchema.optional()
});

export const postAttachmentSchema = z.object({
    id: z.number(),
    fallback: z.string(),
    color: z.union([postAttachmentColorSchema, z.string()]),
    pretext: z.string(),
    author_name: z.string(),
    author_link: z.string(),
    author_icon: z.string(),
    title: z.string(),
    title_link: z.string(),
    text: z.string(),
    fields: z.array(postAttachmentFieldSchema),
    actions: z.array(postActionSchema).optional(),
    image_url: z.string(),
    thumb_url: z.string(),
    footer: z.string(),
    footer_icon: z.string(),
    timestamp: z.union([z.number(), z.string()])
});

export const postSchema: z.ZodSchema<Post> = z.lazy(() => z.object({
    id: z.string(),
    create_at: z.number(),
    update_at: z.number(),
    edit_at: z.number(),
    delete_at: z.number(),
    is_pinned: z.boolean(),
    user_id: z.string(),
    channel_id: z.string(),
    root_id: z.string(),
    original_id: z.string(),
    message: z.string(),
    type: postTypeSchema,
    props: z.object({
        app_bindings: z.array(z.any()).optional(),
        attachments: z.array(postAttachmentSchema).optional(),
        from_bot: z.union([z.literal("true"), z.literal("false")]).optional()
    }).optional(),
    hashtags: z.string(),
    pending_post_id: z.string(),
    reply_count: z.number(),
    file_ids: z.array(z.string()).optional(),
    metadata: postMetadataSchema,
    failed: z.boolean().optional(),
    user_activity_posts: z.array(postSchema).optional(),
    state: postStateSchema.optional(),
    filenames: z.array(z.string()).optional(),
    last_reply_at: z.number().optional(),
    participants: z.array(z.union([z.any(), z.string()])).optional(),
    message_source: z.string().optional(),
    is_following: z.boolean().optional(),
    exists: z.boolean().optional()
}));

export const postMetadataSchema: z.ZodSchema<PostMetadata> = z.lazy(() => z.object({
    embeds: z.array(postEmbedSchema),
    emojis: z.array(customEmojiSchema),
    files: z.array(fileInfoSchema),
    images: z.record(z.string(), postImageSchema),
    reactions: z.array(reactionSchema).optional(),
    priority: postPriorityMetadataSchema.optional(),
    acknowledgements: z.array(postAcknowledgementSchema).optional()
}));

export const postEmbedSchema: z.ZodSchema<PostEmbed> = z.lazy(() => z.object({
    type: postEmbedTypeSchema,
    url: z.string(),
    data: z.union([openGraphMetadataSchema, postPreviewMetadataSchema]).optional()
}));

export const postPreviewMetadataSchema: z.ZodSchema<PostPreviewMetadata> = z.lazy(() => z.object({
    post_id: z.string(),
    post: postSchema.optional(),
    channel_display_name: z.string(),
    team_name: z.string(),
    channel_type: z.string(),
    channel_id: z.string()
}));

export const postListResponseSchema: z.ZodSchema<PostListResponse> = z.lazy(() => z.object({
    order: z.array(z.string()),
    posts: z.record(z.string(), postSchema),
    next_post_id: z.string(),
    prev_post_id: z.string(),
    first_inaccessible_post_time: z.number()
}));

export const paginatedPostListResponseSchema: z.ZodSchema<PaginatedPostListResponse> = z.lazy(() => postListResponseSchema.extend({
    has_next: z.boolean()
}));

export const postSearchResponseSchema: z.ZodSchema<PostSearchResponse> = z.lazy(() => postListResponseSchema.extend({
    matches: z.record(z.string(), z.array(z.string()))
}));
