// Generated by ts-to-zod
import { z } from "zod";

export const postsUsageResponseSchema = z.object({
    count: z.number()
});

export const postNotificationResponseSchema = z.object({
    status: z.union([z.literal("error"), z.literal("not_sent"), z.literal("unsupported"), z.literal("success")]),
    reason: z.string().optional(),
    data: z.string().optional()
});

const postSchema = z.any();

export const postListResponseSchema = z.object({
    order: z.array(z.string()),
    posts: z.record(z.string(), postSchema),
    next_post_id: z.string(),
    prev_post_id: z.string(),
    first_inaccessible_post_time: z.number()
});

export const paginatedPostListResponseSchema = postListResponseSchema.extend({
    has_next: z.boolean()
});

export const postSearchResponseSchema = postListResponseSchema.extend({
    matches: z.record(z.string(), z.array(z.string()))
});
