// Generated by ts-to-zod
import { z } from "zod";

export const reactionSchema = z.object({
    user_id: z.string(),
    post_id: z.string(),
    emoji_name: z.string(),
    create_at: z.number()
});
