// Generated by ts-to-zod
import { z } from "zod";
import { RolePermission } from "./roles";

export const rolePermissionSchema = z.enum(RolePermission);

export const roleSchema = z.object({
    id: z.string(),
    name: z.string(),
    display_name: z.string(),
    description: z.string(),
    create_at: z.number(),
    update_at: z.number(),
    delete_at: z.number(),
    permissions: z.array(z.union([rolePermissionSchema, z.string()])),
    scheme_managed: z.boolean(),
    built_in: z.boolean()
});
