// Generated by ts-to-zod
import { z } from "zod";
import { TeamType } from "./teams";

export const teamTypeSchema = z.enum(TeamType);

export const teamsUsageResponseSchema = z.object({
    active: z.number(),
    cloud_archived: z.number()
});

export const teamUnreadSchema = z.object({
    team_id: z.string(),
    mention_count: z.number(),
    mention_count_root: z.number(),
    msg_count: z.number(),
    msg_count_root: z.number(),
    thread_count: z.number().optional(),
    thread_mention_count: z.number().optional(),
    thread_urgent_mention_count: z.number().optional()
});

export const teamMembershipSchema = teamUnreadSchema.extend({
    user_id: z.string(),
    roles: z.string(),
    delete_at: z.number(),
    scheme_admin: z.boolean(),
    scheme_guest: z.boolean(),
    scheme_user: z.boolean()
});

export const teamSchema = z.object({
    id: z.string(),
    create_at: z.number(),
    update_at: z.number(),
    delete_at: z.number(),
    display_name: z.string(),
    name: z.string(),
    description: z.string(),
    email: z.string(),
    type: teamTypeSchema,
    company_name: z.string(),
    allowed_domains: z.string(),
    invite_id: z.string(),
    allow_open_invite: z.boolean(),
    scheme_id: z.string(),
    group_constrained: z.boolean(),
    policy_id: z.string().optional().nullable(),
    last_team_icon_update: z.number().optional()
});

export const getTeamMembersOptsSchema = z.object({
    sort: z.literal("Username").optional(),
    exclude_deleted_users: z.boolean().optional()
});

export const teamsWithCountSchema = z.object({
    teams: z.array(teamSchema),
    total_count: z.number()
});

export const teamStatsSchema = z.object({
    team_id: z.string(),
    total_member_count: z.number(),
    active_member_count: z.number()
});

export const notPagedTeamSearchOptsSchema = z.object({
    allow_open_invite: z.boolean().optional(),
    group_constrained: z.boolean().optional()
});

export const pagedTeamSearchOptsSchema = notPagedTeamSearchOptsSchema.extend({
    page: z.number(),
    per_page: z.number()
});

export const teamInviteWithErrorSchema = z.object({
    email: z.string(),
    error: z.object({
        id: z.string(),
        message: z.string()
    })
});

export const teamSearchOptsSchema = z.union([pagedTeamSearchOptsSchema, notPagedTeamSearchOptsSchema]);
