// Generated by ts-to-zod
import { z } from "zod";
import { UserNotify, UserCallSound, UserStatusValue, CustomStatusDuration } from "./users";

export const userTimezoneSchema = z.object({
    useAutomaticTimezone: z.union([z.boolean(), z.literal("true"), z.literal("false")]),
    automaticTimezone: z.string(),
    manualTimezone: z.string()
});

export const userNotifySchema = z.enum(UserNotify);

export const userCallSoundSchema = z.enum(UserCallSound);

export const userStatusValueSchema = z.enum(UserStatusValue);

export const customStatusDurationSchema = z.enum(CustomStatusDuration);

export const notifyPropsSchema = z.object({
    channel: z.union([z.literal("true"), z.literal("false")]),
    comments: z.union([z.literal("never"), z.literal("root"), z.literal("any")]),
    desktop: userNotifySchema,
    desktop_sound: z.union([z.literal("true"), z.literal("false")]),
    desktop_threads: userNotifySchema.optional(),
    desktop_notification_sound: z.union([z.literal("Bing"), z.literal("Crackle"), z.literal("Down"), z.literal("Hello"), z.literal("Ripple"), z.literal("Upstairs")]).optional(),
    email: z.union([z.literal("true"), z.literal("false")]),
    email_threads: userNotifySchema.optional(),
    first_name: z.union([z.literal("true"), z.literal("false")]),
    loop_mobile_push_reactions: userNotifySchema.optional(),
    loop_mobile_push_reactions_sound: z.union([z.literal("true"), z.literal("false")]).optional(),
    loop_push_reactions: userNotifySchema.optional(),
    loop_push_reactions_sound: z.union([z.literal("true"), z.literal("false")]).optional(),
    mention_keys: z.string(),
    push: userNotifySchema,
    push_status: z.union([z.literal("ooo"), z.literal("offline"), z.literal("away"), z.literal("dnd"), z.literal("online")]),
    push_threads: userNotifySchema.optional(),
    auto_responder_active: z.union([z.literal("true"), z.literal("false")]).optional(),
    auto_responder_message: z.string().optional(),
    calls_notification_sound: userCallSoundSchema.optional(),
    calls_desktop_sound: z.union([z.literal("true"), z.literal("false")]).optional(),
    calls_mobile_sound: z.union([z.literal("true"), z.literal("false"), z.literal("")]).optional(),
    calls_mobile_notification_sound: userCallSoundSchema.optional()
});

export const userProfileSchema = z.object({
    id: z.string(),
    username: z.union([z.string(), z.literal("")]).default(""),
    auth_data: z.union([z.string(), z.literal("")]).default(""),
    auth_service: z.union([z.string(), z.literal("")]).default(""),
    email: z.string(),
    email_verified: z.boolean().optional(),
    nickname: z.string().default(""),
    first_name: z.string().default(""),
    last_name: z.string().default(""),
    position: z.string().default(""),
    password: z.string().optional().describe("excluded from responses"),
    create_at: z.number().describe("Creation date unix timestamp"),
    update_at: z.number().describe("Update date unix timestamp"),
    delete_at: z.union([z.number(), z.literal(0)]).optional().describe("Deletion date unix timestamp\nWill be zero if user is active").default(0),
    roles: z.string().describe("User roles in string format"),
    props: z.record(z.string(), z.unknown()).and(z.object({
        customStatus: z.string().optional().describe("User custom status in stringified format")
    })).optional().describe("User profile props"),
    notify_props: notifyPropsSchema.describe("Notification settings"),
    last_password_update: z.number().optional().describe("Last password update timestamp"),
    last_picture_update: z.number().optional().describe("Will be undefined if no picture was set"),
    locale: z.string().default("'en'"),
    timezone: userTimezoneSchema.optional(),
    remote_id: z.union([z.string(), z.literal("")]).optional().default(""),
    disable_welcome_email: z.boolean().optional(),
    status: z.string().optional(),
    mfa_active: z.boolean().optional(),
    last_activity_at: z.number().optional(),
    is_bot: z.boolean().optional(),
    bot_description: z.string().optional(),
    terms_of_service_id: z.string().optional(),
    terms_of_service_create_at: z.number().optional()
});

export const userStatusSchema = z.object({
    user_id: z.string(),
    status: userStatusValueSchema,
    manual: z.boolean().optional(),
    last_activity_at: z.number().optional(),
    active_channel: z.string().optional(),
    dnd_end_time: z.number().optional()
});

export const userCustomStatusSchema = z.object({
    emoji: z.string(),
    text: z.string(),
    duration: customStatusDurationSchema,
    expires_at: z.string().optional()
});

export const userAccessTokenSchema = z.object({
    id: z.string(),
    token: z.string().optional(),
    user_id: z.string(),
    description: z.string(),
    is_active: z.boolean()
});

export const usersStatsSchema = z.object({
    total_users_count: z.number()
});

export const getFilteredUsersStatsOptsSchema = z.object({
    in_team: z.string().optional(),
    in_channel: z.string().optional(),
    include_deleted: z.boolean().optional(),
    include_bots: z.boolean().optional(),
    include_remote_users: z.boolean().optional(),
    roles: z.array(z.string()).optional(),
    channel_roles: z.array(z.string()).optional(),
    team_roles: z.array(z.string()).optional()
});

export const authChangeResponseSchema = z.object({
    follow_link: z.string()
});

const teamMembershipSchema = z.any();

export const userProfileWithLastViewedAtSchema = userProfileSchema.extend({
    last_viewed_at: z.number()
});

export const userSessionSchema = z.object({
    id: z.string(),
    token: z.string(),
    create_at: z.number(),
    expires_at: z.number(),
    last_activity_at: z.number(),
    user_id: z.string(),
    device_id: z.string(),
    roles: z.string(),
    is_oauth: z.boolean(),
    props: z.record(z.string(), z.unknown()),
    team_members: z.array(teamMembershipSchema),
    local: z.boolean()
});
