// Generated by ts-to-zod
import { z } from "zod";
import { UserNotify, UserNotifyComments, UserNotifyDesktopSound, UserNotifyMarkUnread, UserCallSound, PushStatus, UserStatusValue, CustomStatusDuration } from "./users";

export const userNotifySchema = z.enum(UserNotify);

export const userNotifyCommentsSchema = z.enum(UserNotifyComments);

export const userNotifyDesktopSoundSchema = z.enum(UserNotifyDesktopSound);

export const userNotifyMarkUnreadSchema = z.enum(UserNotifyMarkUnread);

export const userCallSoundSchema = z.enum(UserCallSound);

export const pushStatusSchema = z.enum(PushStatus);

export const userStatusValueSchema = z.enum(UserStatusValue);

export const customStatusDurationSchema = z.enum(CustomStatusDuration);

export const userCustomStatusSchema = z.object({
    emoji: z.string(),
    text: z.string(),
    duration: customStatusDurationSchema,
    expires_at: z.string().optional()
});

export const userTimezoneSchema = z.object({
    useAutomaticTimezone: z.union([z.boolean(), z.string()]),
    automaticTimezone: z.string(),
    manualTimezone: z.string()
});

export const userStatusSchema = z.object({
    user_id: z.string(),
    status: userStatusValueSchema,
    manual: z.boolean().optional(),
    last_activity_at: z.number().optional(),
    active_channel: z.string().optional(),
    dnd_end_time: z.number().optional()
});

export const userAccessTokenSchema = z.object({
    id: z.string(),
    token: z.string().optional(),
    user_id: z.string(),
    description: z.string(),
    is_active: z.boolean()
});

export const usersStatsSchema = z.object({
    total_users_count: z.number()
});

export const getFilteredUsersStatsOptsSchema = z.object({
    in_team: z.string().optional(),
    in_channel: z.string().optional(),
    include_deleted: z.boolean().optional(),
    include_bots: z.boolean().optional(),
    include_remote_users: z.boolean().optional(),
    roles: z.array(z.string()).optional(),
    channel_roles: z.array(z.string()).optional(),
    team_roles: z.array(z.string()).optional()
});

export const authChangeResponseSchema = z.object({
    follow_link: z.string()
});

const stringNullSchema = z.any();

const teamMembershipSchema = z.any();

export const notifyPropsSchema = z.object({
    channel: z.string(),
    comments: userNotifyCommentsSchema,
    desktop: userNotifySchema,
    desktop_sound: z.string(),
    desktop_threads: userNotifySchema.optional(),
    email: z.string(),
    email_threads: userNotifySchema.optional(),
    first_name: z.string(),
    loop_mobile_push_reactions: userNotifySchema.optional(),
    loop_mobile_push_reactions_sound: z.string().optional(),
    loop_push_reactions: userNotifySchema.optional(),
    loop_push_reactions_sound: z.string().optional(),
    mention_keys: z.string(),
    push: userNotifySchema,
    push_status: pushStatusSchema,
    push_threads: userNotifySchema.optional(),
    calls_desktop_sound: z.string().optional(),
    desktop_notification_sound: userNotifyDesktopSoundSchema.optional(),
    calls_notification_sound: userCallSoundSchema.optional(),
    auto_responder_active: z.string().optional(),
    auto_responder_message: z.string().optional(),
    calls_mobile_sound: z.union([z.string(), stringNullSchema]).optional(),
    calls_mobile_notification_sound: userCallSoundSchema.optional()
});

export const userProfileSchema = z.object({
    id: z.string(),
    create_at: z.number().describe("unix format"),
    update_at: z.number().describe("unix format"),
    delete_at: z.number().describe("unix format"),
    username: z.string().default("''"),
    auth_data: z.string().default("''"),
    auth_service: z.string().default("''"),
    email: z.string(),
    email_verified: z.boolean().optional(),
    nickname: z.string().default("''"),
    first_name: z.string().default("''"),
    last_name: z.string().default("''"),
    position: z.string().default("''"),
    password: z.string().optional().describe("excluded from responses"),
    roles: z.string().describe("User roles in string format"),
    props: z.record(z.string(), z.unknown()).and(z.object({
        customStatus: userCustomStatusSchema.optional()
    })).optional(),
    notify_props: notifyPropsSchema,
    last_password_update: z.number(),
    last_picture_update: z.number().optional().describe("Will be undefined if no picture was set"),
    locale: z.string().default("'en'"),
    timezone: userTimezoneSchema.optional(),
    remote_id: z.string().optional().default("''"),
    disable_welcome_email: z.boolean().optional(),
    status: z.string().optional(),
    mfa_active: z.boolean().optional(),
    last_activity_at: z.number().optional(),
    is_bot: z.boolean().optional(),
    bot_description: z.string().optional(),
    terms_of_service_id: z.string().optional(),
    terms_of_service_create_at: z.number().optional()
});

export const userProfileWithLastViewAtSchema = userProfileSchema.extend({
    last_viewed_at: z.number()
});

export const userSessionSchema = z.object({
    id: z.string(),
    token: z.string(),
    create_at: z.number(),
    expires_at: z.number(),
    last_activity_at: z.number(),
    user_id: z.string(),
    device_id: z.string(),
    roles: z.string(),
    is_oauth: z.boolean(),
    props: z.record(z.string(), z.unknown()),
    team_members: z.array(teamMembershipSchema),
    local: z.boolean()
});
