/**
 * A dictionary of codes for errors produced by this package
 */
export enum ErrorCode {
	HTTPError = "http_error",
	OptionsError = "options_error",
	RateLimitedError = "rate_limited_error",
	RequestError = "request_error",
	ServerError = "server_error"
}

const hasMessage = (obj: unknown): obj is { message: string } =>
	Boolean(
		obj &&
			typeof obj === "object" &&
			"message" in obj &&
			typeof obj["message"] === "string"
	);

export class ServerError extends Error {
	/**
	 * @description Error id
	 * @example app.user.missing_account.const
	 */
	id: ServerErrorID;
	override message: string;
	request_id: string;
	detailed_error?: string;
	status_code: number;

	constructor(
		id: ServerErrorID,
		message: string,
		status_code: number,
		request_id: string,
		detailed_error = ""
	) {
		super();
		this.id = id;
		this.message = message;
		this.status_code = Number(status_code);
		this.request_id = request_id;
		this.detailed_error = detailed_error;
	}
}

export class WebClientCodedError extends Error {
	code!: ErrorCode;
}

export class WebClientOptionsError implements WebClientCodedError {
	name = WebClientOptionsError.name;
	code = ErrorCode.RequestError;
	message: string;

	constructor(message: string) {
		this.message = message;
	}
}

export class WebAPIServerError extends WebClientCodedError {
	override name = WebAPIServerError.name;
	override code = ErrorCode.ServerError;
	original: ServerError;

	constructor(error: ServerError) {
		super(error.message);
		this.original = error;
	}
}

export class WebAPIRateLimitedError extends WebAPIServerError {
	override name = WebAPIRateLimitedError.name;
	override code = ErrorCode.RateLimitedError;

	constructor(error: ServerError) {
		super(error);
		this.message = `Rate limited: ${error.message}`;
	}
}

export class WebAPIRequestError extends WebClientCodedError {
	override name = WebAPIRequestError.name;
	override code = ErrorCode.RequestError;
	original: unknown;

	constructor(original: unknown) {
		super(
			`A request error occurred: ${hasMessage(original) ? original.message : JSON.stringify(original, null, 2)}`
		);
		this.original = original;
	}
}

export const isServerError = (error: unknown): error is ServerError => {
	if (!error) return false;
	if (
		typeof error === "object" &&
		"id" in error &&
		"message" in error &&
		"status_code" in error
	) {
		return true;
	}

	return false;
};

export enum ServerErrorID {
	AccessControlPolicyGetChannelsLimit = "api.access_control_policy.get_channels.limit.app_error",
	AccessControlPolicyGetFieldsLimit = "api.access_control_policy.get_fields.limit.app_error",
	AcknowledgementDeleteArchivedChannel = "api.acknowledgement.delete.archived_channel.app_error",
	AcknowledgementDeleteDeadline = "api.acknowledgement.delete.deadline.app_error",
	AcknowledgementSaveArchivedChannel = "api.acknowledgement.save.archived_channel.app_error",
	AdminAddCertificate = "api.admin.add_certificate.app_error",
	AdminAddCertificateArray = "api.admin.add_certificate.array.app_error",
	AdminAddCertificateMultipleFiles = "api.admin.add_certificate.multiple_files.app_error",
	AdminAddCertificateNoFile = "api.admin.add_certificate.no_file.app_error",
	AdminAddCertificateOpen = "api.admin.add_certificate.open.app_error",
	AdminAddCertificateParseform = "api.admin.add_certificate.parseform.app_error",
	AdminAddCertificateSaving = "api.admin.add_certificate.saving.app_error",
	AdminGetBrandImageStorage = "api.admin.get_brand_image.storage.app_error",
	AdminLdapNotAvailable = "api.admin.ldap.not_available.app_error",
	AdminRemoveCertificate = "api.admin.remove_certificate.app_error",
	AdminRemoveCertificateDelete = "api.admin.remove_certificate.delete.app_error",
	AdminSamlFailureGetMetadataFromIdp = "api.admin.saml.failure_get_metadata_from_idp.app_error",
	AdminSamlFailureParseIdpCertificate = "api.admin.saml.failure_parse_idp_certificate.app_error",
	AdminSamlFailureResetAuthdataToEmail = "api.admin.saml.failure_reset_authdata_to_email.app_error",
	AdminSamlFailureSaveIdpCertificateFile = "api.admin.saml.failure_save_idp_certificate_file.app_error",
	AdminSamlInvalidXmlMissingIdpssodescriptors = "api.admin.saml.invalid_xml_missing_idpssodescriptors.app_error",
	AdminSamlInvalidXmlMissingKeydescriptor = "api.admin.saml.invalid_xml_missing_keydescriptor.app_error",
	AdminSamlInvalidXmlMissingSsoservices = "api.admin.saml.invalid_xml_missing_ssoservices.app_error",
	AdminSamlMetadata = "api.admin.saml.metadata.app_error",
	AdminSamlNotAvailable = "api.admin.saml.not_available.app_error",
	AdminSamlSetCertificateFromMetadataInvalidBody = "api.admin.saml.set_certificate_from_metadata.invalid_body.app_error",
	AdminSamlSetCertificateFromMetadataInvalidContentType = "api.admin.saml.set_certificate_from_metadata.invalid_content_type.app_error",
	AdminSamlSetCertificateFromMetadataMissingContentType = "api.admin.saml.set_certificate_from_metadata.missing_content_type.app_error",
	AdminUploadBrandImageArray = "api.admin.upload_brand_image.array.app_error",
	AdminUploadBrandImageNoFile = "api.admin.upload_brand_image.no_file.app_error",
	AdminUploadBrandImageParse = "api.admin.upload_brand_image.parse.app_error",
	AdminUploadBrandImageStorage = "api.admin.upload_brand_image.storage.app_error",
	AdminUploadBrandImageTooLarge = "api.admin.upload_brand_image.too_large.app_error",
	ChannelAddUserToChannelFailed = "api.channel.add_user.to.channel.failed.app_error",
	ChannelAddUserToChannelFailedDeleted = "api.channel.add_user.to.channel.failed.deleted.app_error",
	ChannelAddUserToChannelType = "api.channel.add_user_to_channel.type.app_error",
	ChannelBookmarkCreateChannelBookmarkDeletedChannelForbidden = "api.channel.bookmark.create_channel_bookmark.deleted_channel.forbidden.app_error",
	ChannelBookmarkCreateChannelBookmarkDirectOrGroupChannelsByGuestsForbidden = "api.channel.bookmark.create_channel_bookmark.direct_or_group_channels_by_guests.forbidden.app_error",
	ChannelBookmarkCreateChannelBookmarkDirectOrGroupChannelsForbidden = "api.channel.bookmark.create_channel_bookmark.direct_or_group_channels.forbidden.app_error",
	ChannelBookmarkCreateChannelBookmarkForbidden = "api.channel.bookmark.create_channel_bookmark.forbidden.app_error",
	ChannelBookmarkDeleteChannelBookmarkDeletedChannelForbidden = "api.channel.bookmark.delete_channel_bookmark.deleted_channel.forbidden.app_error",
	ChannelBookmarkDeleteChannelBookmarkDirectOrGroupChannelsByGuestsForbidden = "api.channel.bookmark.delete_channel_bookmark.direct_or_group_channels_by_guests.forbidden.app_error",
	ChannelBookmarkDeleteChannelBookmarkDirectOrGroupChannelsForbidden = "api.channel.bookmark.delete_channel_bookmark.direct_or_group_channels.forbidden.app_error",
	ChannelBookmarkDeleteChannelBookmarkForbidden = "api.channel.bookmark.delete_channel_bookmark.forbidden.app_error",
	ChannelBookmarkUpdateChannelBookmarkDeletedChannelForbidden = "api.channel.bookmark.update_channel_bookmark.deleted_channel.forbidden.app_error",
	ChannelBookmarkUpdateChannelBookmarkDirectOrGroupChannelsByGuestsForbidden = "api.channel.bookmark.update_channel_bookmark.direct_or_group_channels_by_guests.forbidden.app_error",
	ChannelBookmarkUpdateChannelBookmarkDirectOrGroupChannelsForbidden = "api.channel.bookmark.update_channel_bookmark.direct_or_group_channels.forbidden.app_error",
	ChannelBookmarkUpdateChannelBookmarkForbidden = "api.channel.bookmark.update_channel_bookmark.forbidden.app_error",
	ChannelBookmarkUpdateChannelBookmarkSortOrderDeletedChannelForbidden = "api.channel.bookmark.update_channel_bookmark_sort_order.deleted_channel.forbidden.app_error",
	ChannelBookmarkUpdateChannelBookmarkSortOrderDirectOrGroupChannelsByGuestsForbidden = "api.channel.bookmark.update_channel_bookmark_sort_order.direct_or_group_channels_by_guests.forbidden.app_error",
	ChannelBookmarkUpdateChannelBookmarkSortOrderDirectOrGroupChannelsForbidden = "api.channel.bookmark.update_channel_bookmark_sort_order.direct_or_group_channels.forbidden.app_error",
	ChannelBookmarkUpdateChannelBookmarkSortOrderForbidden = "api.channel.bookmark.update_channel_bookmark_sort_order.forbidden.app_error",
	ChannelCreateChannelDirectChannel = "api.channel.create_channel.direct_channel.app_error",
	ChannelCreateChannelDirectChannelRemoteRestricted = "api.channel.create_channel.direct_channel.remote_restricted.app_error",
	ChannelCreateChannelMaxChannelLimit = "api.channel.create_channel.max_channel_limit.app_error",
	ChannelCreateDirectChannelInvalidUser = "api.channel.create_direct_channel.invalid_user.app_error",
	ChannelCreateGroupBadSize = "api.channel.create_group.bad_size.app_error",
	ChannelCreateGroupBadUser = "api.channel.create_group.bad_user.app_error",
	ChannelCreateGroupRemoteRestricted = "api.channel.create_group.remote_restricted.app_error",
	ChannelDeleteChannelCannot = "api.channel.delete_channel.cannot.app_error",
	ChannelDeleteChannelDeleted = "api.channel.delete_channel.deleted.app_error",
	ChannelGetChannelFlaggedPostMismatch = "api.channel.get_channel.flagged_post_mismatch.app_error",
	ChannelJoinChannelPermissions = "api.channel.join_channel.permissions.app_error",
	ChannelLeaveDefault = "api.channel.leave.default.app_error",
	ChannelLeaveDirect = "api.channel.leave.direct.app_error",
	ChannelPatchChannelModerationsForChannelRestrictedPermission = "api.channel.patch_channel_moderations_for_channel.restricted_permission.app_error",
	ChannelPatchUpdateChannelForbidden = "api.channel.patch_update_channel.forbidden.app_error",
	ChannelPatchUpdateChannelRestrictedDm = "api.channel.patch_update_channel.restricted_dm.app_error",
	ChannelPatchUpdateChannelUpdateDirectOrGroupMessagesNotAllowed = "api.channel.patch_update_channel.update_direct_or_group_messages_not_allowed.app_error",
	ChannelRemoveChannelMemberType = "api.channel.remove_channel_member.type.app_error",
	ChannelRemoveDefault = "api.channel.remove.default.app_error",
	ChannelRemoveMemberGroupConstrained = "api.channel.remove_member.group_constrained.app_error",
	ChannelRemoveUserFromChannel = "api.channel.remove_user_from_channel.app_error",
	ChannelRenameChannelCantRenameDirectMessages = "api.channel.rename_channel.cant_rename_direct_messages.app_error",
	ChannelRenameChannelCantRenameGroupMessages = "api.channel.rename_channel.cant_rename_group_messages.app_error",
	ChannelRestoreChannelRestored = "api.channel.restore_channel.restored.app_error",
	ChannelUpdateChannelDeleted = "api.channel.update_channel.deleted.app_error",
	ChannelUpdateChannelMemberRolesChangingGuestRole = "api.channel.update_channel_member_roles.changing_guest_role.app_error",
	ChannelUpdateChannelMemberRolesGuest = "api.channel.update_channel_member_roles.guest.app_error",
	ChannelUpdateChannelMemberRolesGuestAndUser = "api.channel.update_channel_member_roles.guest_and_user.app_error",
	ChannelUpdateChannelMemberRolesSchemeRole = "api.channel.update_channel_member_roles.scheme_role.app_error",
	ChannelUpdateChannelMemberRolesUnsetUserScheme = "api.channel.update_channel_member_roles.unset_user_scheme.app_error",
	ChannelUpdateChannelMemberRolesUserAndGuest = "api.channel.update_channel_member_roles.user_and_guest.app_error",
	ChannelUpdateChannelNotAllowed = "api.channel.update_channel.not_allowed.app_error",
	ChannelUpdateChannelTried = "api.channel.update_channel.tried.app_error",
	ChannelUpdateChannelTypechange = "api.channel.update_channel.typechange.app_error",
	ChannelUpdateChannelUpdateDirectOrGroupMessagesNotAllowed = "api.channel.update_channel.update_direct_or_group_messages_not_allowed.app_error",
	ChannelUpdateTeamMemberRolesChangingGuestRole = "api.channel.update_team_member_roles.changing_guest_role.app_error",
	ChannelUpdateTeamMemberRolesSchemeRole = "api.channel.update_team_member_roles.scheme_role.app_error",
	Cloud = "api.cloud.app_error",
	CommandAdminOnly = "api.command.admin_only.app_error",
	CommandChannelHeaderChannel = "api.command_channel_header.channel.app_error",
	CommandChannelHeaderMessage = "api.command_channel_header.message.app_error",
	CommandChannelHeaderPermission = "api.command_channel_header.permission.app_error",
	CommandChannelHeaderUpdateChannel = "api.command_channel_header.update_channel.app_error",
	CommandChannelPurposeChannel = "api.command_channel_purpose.channel.app_error",
	CommandChannelPurposeDirectGroup = "api.command_channel_purpose.direct_group.app_error",
	CommandChannelPurposeMessage = "api.command_channel_purpose.message.app_error",
	CommandChannelPurposePermission = "api.command_channel_purpose.permission.app_error",
	CommandChannelPurposeUpdateChannel = "api.command_channel_purpose.update_channel.app_error",
	CommandChannelRemoveChannel = "api.command_channel_remove.channel.app_error",
	CommandChannelRenameChannel = "api.command_channel_rename.channel.app_error",
	CommandChannelRenameDirectGroup = "api.command_channel_rename.direct_group.app_error",
	CommandChannelRenameMessage = "api.command_channel_rename.message.app_error",
	CommandChannelRenamePermission = "api.command_channel_rename.permission.app_error",
	CommandChannelRenameTooLong = "api.command_channel_rename.too_long.app_error",
	CommandChannelRenameTooShort = "api.command_channel_rename.too_short.app_error",
	CommandChannelRenameUpdateChannel = "api.command_channel_rename.update_channel.app_error",
	CommandCodeMessage = "api.command_code.message.app_error",
	CommandCommandPostForbidden = "api.command.command_post.forbidden.app_error",
	CommandCustomStatus = "api.command_custom_status.app_error",
	CommandCustomStatusClear = "api.command_custom_status.clear.app_error",
	CommandDisabled = "api.command.disabled.app_error",
	CommandDuplicateTrigger = "api.command.duplicate_trigger.app_error",
	CommandEchoDelay = "api.command_echo.delay.app_error",
	CommandEchoHighVolume = "api.command_echo.high_volume.app_error",
	CommandEchoMessage = "api.command_echo.message.app_error",
	CommandExecuteCommandCreatePostFailed = "api.command.execute_command.create_post_failed.app_error",
	CommandExecuteCommandFailed = "api.command.execute_command.failed.app_error",
	CommandExecuteCommandFailedEmpty = "api.command.execute_command.failed_empty.app_error",
	CommandExecuteCommandFailedResp = "api.command.execute_command.failed_resp.app_error",
	CommandExecuteCommandFormat = "api.command.execute_command.format.app_error",
	CommandExecuteCommandNotFound = "api.command.execute_command.not_found.app_error",
	CommandExecuteCommandStart = "api.command.execute_command.start.app_error",
	CommandExpandCollapseFail = "api.command_expand_collapse.fail.app_error",
	CommandExportlinkDriver = "api.command_exportlink.driver.app_error",
	CommandExportlinkEmpty = "api.command_exportlink.empty.app_error",
	CommandExportlinkInvalid = "api.command_exportlink.invalid.app_error",
	CommandExportlinkList = "api.command_exportlink.list.app_error",
	CommandExportlinkPermission = "api.command_exportlink.permission.app_error",
	CommandExportlinkPresign = "api.command_exportlink.presign.app_error",
	CommandGroupmsgFail = "api.command_groupmsg.fail.app_error",
	CommandGroupmsgGroupFail = "api.command_groupmsg.group_fail.app_error",
	CommandGroupmsgInvalidUser = "api.command_groupmsg.invalid_user.app_error",
	CommandGroupmsgMaxUsers = "api.command_groupmsg.max_users.app_error",
	CommandGroupmsgMinUsers = "api.command_groupmsg.min_users.app_error",
	CommandGroupmsgPermission = "api.command_groupmsg.permission.app_error",
	CommandInviteChannel = "api.command_invite.channel.app_error",
	CommandInviteDirectchannel = "api.command_invite.directchannel.app_error",
	CommandInviteFail = "api.command_invite.fail.app_error",
	CommandInviteMissingMessage = "api.command_invite.missing_message.app_error",
	CommandInviteMissingUser = "api.command_invite.missing_user.app_error",
	CommandInvitePeoplePermission = "api.command_invite_people.permission.app_error",
	CommandInvitePermission = "api.command_invite.permission.app_error",
	CommandInvitePrivateChannel = "api.command_invite.private_channel.app_error",
	CommandInviteUserAlreadyInChannel = "api.command_invite.user_already_in_channel.app_error",
	CommandInviteUserNotInTeam = "api.command_invite.user_not_in_team.app_error",
	CommandJoinFail = "api.command_join.fail.app_error",
	CommandJoinList = "api.command_join.list.app_error",
	CommandJoinMissing = "api.command_join.missing.app_error",
	CommandLeaveFail = "api.command_leave.fail.app_error",
	CommandMarketplaceUnsupported = "api.command_marketplace.unsupported.app_error",
	CommandMoveCommandCreatorNoPermission = "api.command.move_command.creator_no_permission.app_error",
	CommandMsgDmFail = "api.command_msg.dm_fail.app_error",
	CommandMsgFail = "api.command_msg.fail.app_error",
	CommandMsgMissing = "api.command_msg.missing.app_error",
	CommandMsgPermission = "api.command_msg.permission.app_error",
	CommandRemoveDirectGroup = "api.command_remove.direct_group.app_error",
	CommandRemoveMessage = "api.command_remove.message.app_error",
	CommandRemoveMissing = "api.command_remove.missing.app_error",
	CommandRemovePermission = "api.command_remove.permission.app_error",
	CommandSearchUnsupported = "api.command_search.unsupported.app_error",
	CommandSettingsUnsupported = "api.command_settings.unsupported.app_error",
	CommandShortcutsUnsupported = "api.command_shortcuts.unsupported.app_error",
	CommandTeamMismatch = "api.command.team_mismatch.app_error",
	ConfigGetConfigRestrictedMerge = "api.config.get_config.restricted_merge.app_error",
	ConfigMigrateConfig = "api.config.migrate_config.app_error",
	ConfigPatchConfigDiff = "api.config.patch_config.diff.app_error",
	ConfigPatchConfigRestrictedMerge = "api.config.patch_config.restricted_merge.app_error",
	ConfigReloadConfig = "api.config.reload_config.app_error",
	ConfigUpdateConfigClearSiteurl = "api.config.update_config.clear_siteurl.app_error",
	ConfigUpdateConfigDiff = "api.config.update_config.diff.app_error",
	ConfigUpdateConfigNotAllowedSecurity = "api.config.update_config.not_allowed_security.app_error",
	ConfigUpdateConfigRestrictedMerge = "api.config.update_config.restricted_merge.app_error",
	ConfigUpdateConfigTranslations = "api.config.update_config.translations.app_error",
	Context404 = "api.context.404.app_error",
	ContextGetSession = "api.context.get_session.app_error",
	ContextGetUser = "api.context.get_user.app_error",
	ContextInvalidBodyParam = "api.context.invalid_body_param.app_error",
	ContextInvalidParam = "api.context.invalid_param.app_error",
	ContextInvalidUrlParam = "api.context.invalid_url_param.app_error",
	ContextIpFilteringApplyIpFilters = "api.context.ip_filtering.apply_ip_filters.app_error",
	ContextIpFilteringGetIpFilters = "api.context.ip_filtering.get_ip_filters.app_error",
	ContextIpFilteringNotAvailable = "api.context.ip_filtering.not_available.app_error",
	ContextJsonEncoding = "api.context.json_encoding.app_error",
	ContextLocalOriginRequired = "api.context.local_origin_required.app_error",
	ContextMfaRequired = "api.context.mfa_required.app_error",
	ContextOutgoingOauthConnectionCreateConnection = "api.context.outgoing_oauth_connection.create_connection.app_error",
	ContextOutgoingOauthConnectionDeleteConnection = "api.context.outgoing_oauth_connection.delete_connection.app_error",
	ContextOutgoingOauthConnectionListConnections = "api.context.outgoing_oauth_connection.list_connections.app_error",
	ContextOutgoingOauthConnectionUpdateConnection = "api.context.outgoing_oauth_connection.update_connection.app_error",
	ContextOutgoingOauthConnectionValidateConnectionCredentials = "api.context.outgoing_oauth_connection.validate_connection_credentials.app_error",
	ContextPermissions = "api.context.permissions.app_error",
	ContextRemoteIdInvalid = "api.context.remote_id_invalid.app_error",
	ContextRemoteIdMismatch = "api.context.remote_id_mismatch.app_error",
	ContextRemoteIdMissing = "api.context.remote_id_missing.app_error",
	ContextRequestBodyTooLarge = "api.context.request_body_too_large.app_error",
	ContextServerBusy = "api.context.server_busy.app_error",
	ContextSessionExpired = "api.context.session_expired.app_error",
	ContextTokenProvided = "api.context.token_provided.app_error",
	CreateTermsOfServiceCustomTermsOfServiceDisabled = "api.create_terms_of_service.custom_terms_of_service_disabled.app_error",
	CreateTermsOfServiceEmptyText = "api.create_terms_of_service.empty_text.app_error",
	CustomStatusRecentCustomStatusesDelete = "api.custom_status.recent_custom_statuses.delete.app_error",
	CustomStatusSetCustomStatusesUpdate = "api.custom_status.set_custom_statuses.update.app_error",
	DraftsDisabled = "api.drafts.disabled.app_error",
	ElasticsearchTestElasticsearchSettingsNil = "api.elasticsearch.test_elasticsearch_settings_nil.app_error",
	EmailBatchingAddNotificationEmailToBatchChannelFull = "api.email_batching.add_notification_email_to_batch.channel_full.app_error",
	EmailBatchingAddNotificationEmailToBatchDisabled = "api.email_batching.add_notification_email_to_batch.disabled.app_error",
	EmojiCreateDuplicate = "api.emoji.create.duplicate.app_error",
	EmojiCreateOtherUser = "api.emoji.create.other_user.app_error",
	EmojiCreateParse = "api.emoji.create.parse.app_error",
	EmojiCreateTooLarge = "api.emoji.create.too_large.app_error",
	EmojiDisabled = "api.emoji.disabled.app_error",
	EmojiGetImageDecode = "api.emoji.get_image.decode.app_error",
	EmojiGetImageRead = "api.emoji.get_image.read.app_error",
	EmojiStorage = "api.emoji.storage.app_error",
	EmojiUploadImage = "api.emoji.upload.image.app_error",
	EmojiUploadLargeImageTooLarge = "api.emoji.upload.large_image.too_large.app_error",
	EmojiUploadOpen = "api.emoji.upload.open.app_error",
	EmojiUploadSeek = "api.emoji.upload.seek.app_error",
	ExportExportNotFound = "api.export.export_not_found.app_error",
	FileAppendFile = "api.file.append_file.app_error",
	FileAttachmentsDisabled = "api.file.attachments.disabled.app_error",
	FileCloudUpload = "api.file.cloud_upload.app_error",
	FileFileExists = "api.file.file_exists.app_error",
	FileFileModTime = "api.file.file_mod_time.app_error",
	FileFileReader = "api.file.file_reader.app_error",
	FileFileSize = "api.file.file_size.app_error",
	FileGetFileInfo = "api.file.get_file_info.app_error",
	FileGetFileInvalidFlaggedPost = "api.file.get_file.invalid_flagged_post.app_error",
	FileGetFilePreviewNoPreview = "api.file.get_file_preview.no_preview.app_error",
	FileGetFilePublicInvalid = "api.file.get_file.public_invalid.app_error",
	FileGetFileThumbnailNoThumbnail = "api.file.get_file_thumbnail.no_thumbnail.app_error",
	FileGetPublicLinkDisabled = "api.file.get_public_link.disabled.app_error",
	FileGetPublicLinkNoPost = "api.file.get_public_link.no_post.app_error",
	FileListDirectory = "api.file.list_directory.app_error",
	FileMoveFile = "api.file.move_file.app_error",
	FileNoDriver = "api.file.no_driver.app_error",
	FileReadFile = "api.file.read_file.app_error",
	FileReadFileReadingLocal = "api.file.read_file.reading_local.app_error",
	FileRemoveDirectory = "api.file.remove_directory.app_error",
	FileRemoveFile = "api.file.remove_file.app_error",
	FileTestConnection = "api.file.test_connection.app_error",
	FileTestConnectionEmailSettingsNil = "api.file.test_connection_email_settings_nil.app_error",
	FileTestConnectionS3Auth = "api.file.test_connection_s3_auth.app_error",
	FileTestConnectionS3BucketDoesNotExist = "api.file.test_connection_s3_bucket_does_not_exist.app_error",
	FileTestConnectionS3SettingsNil = "api.file.test_connection_s3_settings_nil.app_error",
	FileUploadFileGetChannel = "api.file.upload_file.get_channel.app_error",
	FileUploadFileIncorrectChannelid = "api.file.upload_file.incorrect_channelId.app_error",
	FileUploadFileIncorrectNumberOfClientIds = "api.file.upload_file.incorrect_number_of_client_ids.app_error",
	FileUploadFileLargeImage = "api.file.upload_file.large_image.app_error",
	FileUploadFileLargeImageDetailed = "api.file.upload_file.large_image_detailed.app_error",
	FileUploadFileMultipleChannelIds = "api.file.upload_file.multiple_channel_ids.app_error",
	FileUploadFileReadFormValue = "api.file.upload_file.read_form_value.app_error",
	FileUploadFileReadRequest = "api.file.upload_file.read_request.app_error",
	FileUploadFileStorage = "api.file.upload_file.storage.app_error",
	FileUploadFileTooLargeDetailed = "api.file.upload_file.too_large_detailed.app_error",
	FileWriteFile = "api.file.write_file.app_error",
	FileZipFileReader = "api.file.zip_file_reader.app_error",
	ImageGet = "api.image.get.app_error",
	IncomingWebhookDisabled = "api.incoming_webhook.disabled.app_error",
	IncomingWebhookInvalidUsername = "api.incoming_webhook.invalid_username.app_error",
	LdapInvalidTestType = "api.ldap.invalid_test_type.app_error",
	LicenseAddLicenseArray = "api.license.add_license.array.app_error",
	LicenseAddLicenseCopy = "api.license.add_license.copy.app_error",
	LicenseAddLicenseExpired = "api.license.add_license.expired.app_error",
	LicenseAddLicenseInvalid = "api.license.add_license.invalid.app_error",
	LicenseAddLicenseInvalidCount = "api.license.add_license.invalid_count.app_error",
	LicenseAddLicenseNoFile = "api.license.add_license.no_file.app_error",
	LicenseAddLicenseOpen = "api.license.add_license.open.app_error",
	LicenseAddLicenseSave = "api.license.add_license.save.app_error",
	LicenseAddLicenseSaveActive = "api.license.add_license.save_active.app_error",
	LicenseAddLicenseUniqueUsers = "api.license.add_license.unique_users.app_error",
	LicenseClientOldFormat = "api.license.client.old_format.app_error",
	LicenseLoadMetric = "api.license.load_metric.app_error",
	LicenseRequestTrialLicense = "api.license.request_trial_license.app_error",
	LicenseUpgradeNeeded = "api.license.upgrade_needed.app_error",
	MissingChannelMemberError = "app.channel.get_member.missing.app_error",
	MissingAccountError = "app.user.missing_account.const",
	MissingAuthAccountError = "app.user.get_by_auth.missing_account.app_error",
	OauthAllowOauthPkceRequiredPublic = "api.oauth.allow_oauth.pkce_required_public.app_error",
	OauthAllowOauthRedirectCallback = "api.oauth.allow_oauth.redirect_callback.app_error",
	OauthAllowOauthTurnOff = "api.oauth.allow_oauth.turn_off.app_error",
	OauthAuthorizationServerMetadataDisabled = "api.oauth.authorization_server_metadata.disabled.app_error",
	OauthAuthorizationServerMetadataInvalidUrl = "api.oauth.authorization_server_metadata.invalid_url.app_error",
	OauthAuthorizationServerMetadataSiteUrlRequired = "api.oauth.authorization_server_metadata.site_url_required.app_error",
	OauthAuthorizeOauthDisabled = "api.oauth.authorize_oauth.disabled.app_error",
	OauthGetAccessTokenBadClientId = "api.oauth.get_access_token.bad_client_id.app_error",
	OauthGetAccessTokenBadGrant = "api.oauth.get_access_token.bad_grant.app_error",
	OauthGetAccessTokenBadRequest = "api.oauth.get_access_token.bad_request.app_error",
	OauthGetAccessTokenCredentials = "api.oauth.get_access_token.credentials.app_error",
	OauthGetAccessTokenDisabled = "api.oauth.get_access_token.disabled.app_error",
	OauthGetAccessTokenExpiredCode = "api.oauth.get_access_token.expired_code.app_error",
	OauthGetAccessTokenInternal = "api.oauth.get_access_token.internal.app_error",
	OauthGetAccessTokenInternalSaving = "api.oauth.get_access_token.internal_saving.app_error",
	OauthGetAccessTokenInternalSession = "api.oauth.get_access_token.internal_session.app_error",
	OauthGetAccessTokenInternalUser = "api.oauth.get_access_token.internal_user.app_error",
	OauthGetAccessTokenMissingCode = "api.oauth.get_access_token.missing_code.app_error",
	OauthGetAccessTokenMissingRefreshToken = "api.oauth.get_access_token.missing_refresh_token.app_error",
	OauthGetAccessTokenRedirectUri = "api.oauth.get_access_token.redirect_uri.app_error",
	OauthGetAccessTokenRefreshToken = "api.oauth.get_access_token.refresh_token.app_error",
	OauthGetAccessTokenResourceMismatch = "api.oauth.get_access_token.resource_mismatch.app_error",
	OauthInvalidStateToken = "api.oauth.invalid_state_token.app_error",
	OauthRegenerateSecretPublicClient = "api.oauth.regenerate_secret.public_client.app_error",
	OauthRegisterOauthAppTurnOff = "api.oauth.register_oauth_app.turn_off.app_error",
	OauthRevokeAccessTokenDelSession = "api.oauth.revoke_access_token.del_session.app_error",
	OauthRevokeAccessTokenDelToken = "api.oauth.revoke_access_token.del_token.app_error",
	OauthRevokeAccessTokenGet = "api.oauth.revoke_access_token.get.app_error",
	OauthSingupWithOauthDisabled = "api.oauth.singup_with_oauth.disabled.app_error",
	OauthSingupWithOauthExpiredLink = "api.oauth.singup_with_oauth.expired_link.app_error",
	OauthSingupWithOauthInvalidLink = "api.oauth.singup_with_oauth.invalid_link.app_error",
	OutgoingWebhookDisabled = "api.outgoing_webhook.disabled.app_error",
	PluginInstallDownloadFailed = "api.plugin.install.download_failed.app_error",
	PluginUploadArray = "api.plugin.upload.array.app_error",
	PluginUploadFile = "api.plugin.upload.file.app_error",
	PluginUploadFileTooLarge = "api.plugin.upload.file_too_large.app_error",
	PluginUploadNoFile = "api.plugin.upload.no_file.app_error",
	PluginVerifyPlugin = "api.plugin.verify_plugin.app_error",
	PostBurnPostUserNotInChannel = "api.post.burn_post.user_not_in_channel.app_error",
	PostCreatePostBurnOnRead = "api.post.create_post.burn_on_read.app_error",
	PostCreatePostChannelRootId = "api.post.create_post.channel_root_id.app_error",
	PostCreatePostRootId = "api.post.create_post.root_id.app_error",
	PostCreateWebhookPostCreating = "api.post.create_webhook_post.creating.app_error",
	PostDeletePostNotEnabled = "api.post.delete_post.not_enabled.app_error",
	PostDoActionActionId = "api.post.do_action.action_id.app_error",
	PostDoActionActionIntegration = "api.post.do_action.action_integration.app_error",
	PostFillInPostPropsBurnOnReadConfig = "api.post.fill_in_post_props.burn_on_read.config.app_error",
	PostFillInPostPropsBurnOnReadLicense = "api.post.fill_in_post_props.burn_on_read.license.app_error",
	PostFillInPostPropsInvalidAiGeneratedUser = "api.post.fill_in_post_props.invalid_ai_generated_user.app_error",
	PostGetLinkMetadataForPermalinkBurnOnRead = "api.post.get_link_metadata_for_permalink.burn_on_read.app_error",
	PostGetPostByIdGet = "api.post_get_post_by_id.get.app_error",
	PostMoveThreadDisabled = "api.post.move_thread.disabled.app_error",
	PostRevealPostCannotRevealOwnPost = "api.post.reveal_post.cannot_reveal_own_post.app_error",
	PostRevealPostDisabled = "api.post.reveal_post.disabled.app_error",
	PostRevealPostUserNotInChannel = "api.post.reveal_post.user_not_in_channel.app_error",
	PostSearchFilesInvalidBody = "api.post.search_files.invalid_body.app_error",
	PostSearchPostsInvalidBody = "api.post.search_posts.invalid_body.app_error",
	PostUpdatePostBurnOnRead = "api.post.update_post.burn_on_read.app_error",
	PostUpdatePostFind = "api.post.update_post.find.app_error",
	PostUpdatePostPermissionsDetails = "api.post.update_post.permissions_details.app_error",
	PostUpdatePostPermissionsTimeLimit = "api.post.update_post.permissions_time_limit.app_error",
	PostUpdatePostSystemMessage = "api.post.update_post.system_message.app_error",
	PreferenceDeletePreferencesDelete = "api.preference.delete_preferences.delete.app_error",
	PreferenceDeletePreferencesUpdateSidebar = "api.preference.delete_preferences.update_sidebar.app_error",
	PreferencePreferencesCategoryGet = "api.preference.preferences_category.get.app_error",
	PreferenceUpdatePreferencesSet = "api.preference.update_preferences.set.app_error",
	PreferenceUpdatePreferencesUpdateSidebar = "api.preference.update_preferences.update_sidebar.app_error",
	PushNotificationsAckForward = "api.push_notifications_ack.forward.app_error",
	PushNotificationsAckMessageParse = "api.push_notifications_ack.message.parse.app_error",
	PushNotificationsMessageParse = "api.push_notifications.message.parse.app_error",
	PushNotificationDisabled = "api.push_notification.disabled.app_error",
	PushNotificationIdLoadedFetch = "api.push_notification.id_loaded.fetch.app_error",
	ReactionDeleteArchivedChannel = "api.reaction.delete.archived_channel.app_error",
	ReactionSaveArchivedChannel = "api.reaction.save.archived_channel.app_error",
	ReactionSaveBurnOnRead = "api.reaction.save.burn_on_read.app_error",
	ReactionSaveReactionInvalid = "api.reaction.save_reaction.invalid.app_error",
	ReactionSaveReactionUserId = "api.reaction.save_reaction.user_id.app_error",
	RecapDisabled = "api.recap.disabled.app_error",
	RemoteClusterDelete = "api.remote_cluster.delete.app_error",
	RemoteClusterGet = "api.remote_cluster.get.app_error",
	RemoteClusterImportNotAllowed = "api.remote_cluster.import_not_allowed.app_error",
	RemoteClusterInvalidId = "api.remote_cluster.invalid_id.app_error",
	RemoteClusterInvalidTopic = "api.remote_cluster.invalid_topic.app_error",
	RemoteClusterSave = "api.remote_cluster.save.app_error",
	RemoteClusterSaveNotUnique = "api.remote_cluster.save_not_unique.app_error",
	RemoteClusterServiceNotEnabled = "api.remote_cluster.service_not_enabled.app_error",
	RemoteClusterUpdate = "api.remote_cluster.update.app_error",
	RemoteClusterUpdateNotUnique = "api.remote_cluster.update_not_unique.app_error",
	SamlInvalidEmailToken = "api.saml.invalid_email_token.app_error",
	ServerCwsHealthCheck = "api.server.cws.health_check.app_error",
	SlackimportSlackImportOpen = "api.slackimport.slack_import.open.app_error",
	SlackimportSlackImportZip = "api.slackimport.slack_import.zip.app_error",
	StatusUserNotFound = "api.status.user_not_found.app_error",
	SystemIdLoadedNotAvailable = "api.system.id_loaded.not_available.app_error",
	SystemLogsDownloadBytesBuffer = "api.system.logs.download_bytes_buffer.app_error",
	TeamAddTeamMemberInvalidBody = "api.team.add_team_member.invalid_body.app_error",
	TeamAddUserToTeamFromInviteGuest = "api.team.add_user_to_team_from_invite.guest.app_error",
	TeamAddUserToTeamMissingParameter = "api.team.add_user_to_team.missing_parameter.app_error",
	TeamGetTeamFlaggedPostMismatch = "api.team.get_team.flagged_post_mismatch.app_error",
	TeamGetTeamIconFilesettingsNoDriver = "api.team.get_team_icon.filesettings_no_driver.app_error",
	TeamGetTeamIconReadFile = "api.team.get_team_icon.read_file.app_error",
	TeamImportTeamArray = "api.team.import_team.array.app_error",
	TeamImportTeamInteger = "api.team.import_team.integer.app_error",
	TeamImportTeamNoFile = "api.team.import_team.no_file.app_error",
	TeamImportTeamNoImportFrom = "api.team.import_team.no_import_from.app_error",
	TeamImportTeamOpen = "api.team.import_team.open.app_error",
	TeamImportTeamParse = "api.team.import_team.parse.app_error",
	TeamImportTeamUnavailable = "api.team.import_team.unavailable.app_error",
	TeamImportTeamUnknownImportFrom = "api.team.import_team.unknown_import_from.app_error",
	TeamInvalidateAllEmailInvites = "api.team.invalidate_all_email_invites.app_error",
	TeamInviteGuestsChannelInInvalidTeam = "api.team.invite_guests.channel_in_invalid_team.app_error",
	TeamInviteGuestsPolicyEnforcedChannel = "api.team.invite_guests.policy_enforced_channel.app_error",
	TeamInviteGuestsToChannelsInvalidBody = "api.team.invite_guests_to_channels.invalid_body.app_error",
	TeamInviteMembersDisabled = "api.team.invite_members.disabled.app_error",
	TeamInviteMembersInvalidEmail = "api.team.invite_members.invalid_email.app_error",
	TeamInviteMembersNoOne = "api.team.invite_members.no_one.app_error",
	TeamInviteMembersToTeamAndChannelsInvalidBody = "api.team.invite_members_to_team_and_channels.invalid_body.app_error",
	TeamInviteMembersUnableToSendEmail = "api.team.invite_members.unable_to_send_email.app_error",
	TeamInviteMembersUnableToSendEmailWithDefaults = "api.team.invite_members.unable_to_send_email_with_defaults.app_error",
	TeamIsTeamCreationAllowedDisabled = "api.team.is_team_creation_allowed.disabled.app_error",
	TeamIsTeamCreationAllowedDomain = "api.team.is_team_creation_allowed.domain.app_error",
	TeamJoinUserToTeamAllowedDomains = "api.team.join_user_to_team.allowed_domains.app_error",
	TeamRemoveMemberGroupConstrained = "api.team.remove_member.group_constrained.app_error",
	TeamRemoveTeamIconGetTeam = "api.team.remove_team_icon.get_team.app_error",
	TeamRemoveUserFromTeamMissing = "api.team.remove_user_from_team.missing.app_error",
	TeamSetTeamIconArray = "api.team.set_team_icon.array.app_error",
	TeamSetTeamIconCheckImageLimits = "api.team.set_team_icon.check_image_limits.app_error",
	TeamSetTeamIconDecode = "api.team.set_team_icon.decode.app_error",
	TeamSetTeamIconEncode = "api.team.set_team_icon.encode.app_error",
	TeamSetTeamIconGetTeam = "api.team.set_team_icon.get_team.app_error",
	TeamSetTeamIconNoFile = "api.team.set_team_icon.no_file.app_error",
	TeamSetTeamIconOpen = "api.team.set_team_icon.open.app_error",
	TeamSetTeamIconParse = "api.team.set_team_icon.parse.app_error",
	TeamSetTeamIconStorage = "api.team.set_team_icon.storage.app_error",
	TeamSetTeamIconTooLarge = "api.team.set_team_icon.too_large.app_error",
	TeamSetTeamIconWriteFile = "api.team.set_team_icon.write_file.app_error",
	TeamTeamIconUpdate = "api.team.team_icon.update.app_error",
	TeamUpdateRestrictedDomainsMismatch = "api.team.update_restricted_domains.mismatch.app_error",
	TeamUpdateTeamMemberRolesGuest = "api.team.update_team_member_roles.guest.app_error",
	TeamUpdateTeamMemberRolesGuestAndUser = "api.team.update_team_member_roles.guest_and_user.app_error",
	TeamUpdateTeamMemberRolesUnsetUserScheme = "api.team.update_team_member_roles.unset_user_scheme.app_error",
	TeamUpdateTeamMemberRolesUserAndGuest = "api.team.update_team_member_roles.user_and_guest.app_error",
	UpgradeToEnterprise = "api.upgrade_to_enterprise.app_error",
	UpgradeToEnterpriseAlreadyDone = "api.upgrade_to_enterprise.already-done.app_error",
	UpgradeToEnterpriseAlreadyEnterprise = "api.upgrade_to_enterprise.already-enterprise.app_error",
	UpgradeToEnterpriseGenericError = "api.upgrade_to_enterprise.generic_error.app_error",
	UpgradeToEnterpriseInvalidPermission = "api.upgrade_to_enterprise.invalid-permission.app_error",
	UpgradeToEnterpriseInvalidUser = "api.upgrade_to_enterprise.invalid-user.app_error",
	UpgradeToEnterpriseInvalidUserAndPermission = "api.upgrade_to_enterprise.invalid-user-and-permission.app_error",
	UpgradeToEnterpriseStatus = "api.upgrade_to_enterprise_status.app_error",
	UpgradeToEnterpriseStatusSignature = "api.upgrade_to_enterprise_status.signature.app_error",
	UpgradeToEnterpriseSystemNotSupported = "api.upgrade_to_enterprise.system_not_supported.app_error",
	UploadCreateUploadChannelNotSharedWithRemote = "api.upload.create.upload_channel_not_shared_with_remote.app_error",
	UploadCreateUploadTooLarge = "api.upload.create.upload_too_large.app_error",
	UploadGetUploadForbidden = "api.upload.get_upload.forbidden.app_error",
	UploadInvalidTypeForSharedChannel = "api.upload.invalid_type_for_shared_channel.app_error",
	UserActivateMfaEmailAndLdapOnly = "api.user.activate_mfa.email_and_ldap_only.app_error",
	UserAddUserToGroupSyncablesNotLdapUser = "api.user.add_user_to_group_syncables.not_ldap_user.app_error",
	UserAuthorizeOauthUserBadResponse = "api.user.authorize_oauth_user.bad_response.app_error",
	UserAuthorizeOauthUserBadToken = "api.user.authorize_oauth_user.bad_token.app_error",
	UserAuthorizeOauthUserInvalidState = "api.user.authorize_oauth_user.invalid_state.app_error",
	UserAuthorizeOauthUserMissing = "api.user.authorize_oauth_user.missing.app_error",
	UserAuthorizeOauthUserResponse = "api.user.authorize_oauth_user.response.app_error",
	UserAuthorizeOauthUserSamlHookError = "api.user.authorize_oauth_user.saml_hook_error.app_error",
	UserAuthorizeOauthUserSamlResponseTooLong = "api.user.authorize_oauth_user.saml_response_too_long.app_error",
	UserAuthorizeOauthUserService = "api.user.authorize_oauth_user.service.app_error",
	UserAuthorizeOauthUserTokenFailed = "api.user.authorize_oauth_user.token_failed.app_error",
	UserAuthorizeOauthUserUnsupported = "api.user.authorize_oauth_user.unsupported.app_error",
	UserAuthSwitchNotAvailableEmailSignupDisabled = "api.user.auth_switch.not_available.email_signup_disabled.app_error",
	UserAuthSwitchNotAvailableLoginDisabled = "api.user.auth_switch.not_available.login_disabled.app_error",
	UserAutocompleteUsersMissingTeamId = "api.user.autocomplete_users.missing_team_id.app_error",
	UserCheckUserLoginAttemptsTooMany = "api.user.check_user_login_attempts.too_many.app_error",
	UserCheckUserLoginAttemptsTooManyLdap = "api.user.check_user_login_attempts.too_many_ldap.app_error",
	UserCheckUserMfaBadCode = "api.user.check_user_mfa.bad_code.app_error",
	UserCheckUserPasswordInvalid = "api.user.check_user_password.invalid.app_error",
	UserCheckUserPasswordInvalidHash = "api.user.check_user_password.invalid_hash.app_error",
	UserCompleteSwitchWithOauthBlankEmail = "api.user.complete_switch_with_oauth.blank_email.app_error",
	UserCompleteSwitchWithOauthParse = "api.user.complete_switch_with_oauth.parse.app_error",
	UserCreateOauthUserAlreadyAttached = "api.user.create_oauth_user.already_attached.app_error",
	UserCreateOauthUserCreate = "api.user.create_oauth_user.create.app_error",
	UserCreateProfileImageDefaultFont = "api.user.create_profile_image.default_font.app_error",
	UserCreateProfileImageEncode = "api.user.create_profile_image.encode.app_error",
	UserCreateProfileImageInitial = "api.user.create_profile_image.initial.app_error",
	UserCreateUserAcceptedDomain = "api.user.create_user.accepted_domain.app_error",
	UserCreateUserBadTokenEmailData = "api.user.create_user.bad_token_email_data.app_error",
	UserCreateUserDisabled = "api.user.create_user.disabled.app_error",
	UserCreateUserGuestAccountsDisabled = "api.user.create_user.guest_accounts.disabled.app_error",
	UserCreateUserGuestAccountsLicense = "api.user.create_user.guest_accounts.license.app_error",
	UserCreateUserInvalidInvitationType = "api.user.create_user.invalid_invitation_type.app_error",
	UserCreateUserSignupEmailDisabled = "api.user.create_user.signup_email_disabled.app_error",
	UserCreateUserSignupLinkExpired = "api.user.create_user.signup_link_expired.app_error",
	UserCreateUserSignupLinkInvalid = "api.user.create_user.signup_link_invalid.app_error",
	UserDeleteChannelNotEnabled = "api.user.delete_channel.not_enabled.app_error",
	UserDeleteChannelNotEnabledForAdmin = "api.user.delete_channel.not_enabled.for_admin.app_error",
	UserDeleteTeamNotEnabled = "api.user.delete_team.not_enabled.app_error",
	UserDeleteTeamNotEnabledForAdmin = "api.user.delete_team.not_enabled.for_admin.app_error",
	UserDeleteUserNotEnabled = "api.user.delete_user.not_enabled.app_error",
	UserDeleteUserNotEnabledForAdmin = "api.user.delete_user.not_enabled.for_admin.app_error",
	UserDemoteUserToGuestAlreadyGuest = "api.user.demote_user_to_guest.already_guest.app_error",
	UserEmailToLdapNotAvailable = "api.user.email_to_ldap.not_available.app_error",
	UserEmailToOauthNotAvailable = "api.user.email_to_oauth.not_available.app_error",
	UserGetAuthorizationCodeEndpoint = "api.user.get_authorization_code.endpoint.app_error",
	UserGetProfileImagePath = "api.user.get_profile_image_path.app_error",
	UserGetUploadsForUserForbidden = "api.user.get_uploads_for_user.forbidden.app_error",
	UserGetUsersNotInAbacChannelAccessControlUnavailable = "api.user.get_users_not_in_abac_channel.access_control_unavailable.app_error",
	UserGetUsersValidation = "api.user.get_users.validation.app_error",
	UserGetUserByEmailPermissions = "api.user.get_user_by_email.permissions.app_error",
	UserGuestMagicLinkExpiredToken = "api.user.guest_magic_link.expired_token.app_error",
	UserGuestMagicLinkInvalidToken = "api.user.guest_magic_link.invalid_token.app_error",
	UserGuestMagicLinkInvalidTokenType = "api.user.guest_magic_link.invalid_token_type.app_error",
	UserGuestMagicLinkMissingToken = "api.user.guest_magic_link.missing_token.app_error",
	UserGuestMagicLinkUsernameGenerationFailed = "api.user.guest_magic_link.username_generation_failed.app_error",
	UserLdapToEmailNotAvailable = "api.user.ldap_to_email.not_available.app_error",
	UserLdapToEmailNotLdapAccount = "api.user.ldap_to_email.not_ldap_account.app_error",
	UserLoginBlankPwd = "api.user.login.blank_pwd.app_error",
	UserLoginBotLoginForbidden = "api.user.login.bot_login_forbidden.app_error",
	UserLoginByCwsInvalidToken = "api.user.login_by_cws.invalid_token.app_error",
	UserLoginByIntuneAccountLocked = "api.user.login_by_intune.account_locked.app_error",
	UserLoginByIntuneBotLoginForbidden = "api.user.login_by_intune.bot_login_forbidden.app_error",
	UserLoginByIntuneNotAvailable = "api.user.login_by_intune.not_available.app_error",
	UserLoginByIntuneNotConfigured = "api.user.login_by_intune.not_configured.app_error",
	UserLoginByOauthBotLoginForbidden = "api.user.login_by_oauth.bot_login_forbidden.app_error",
	UserLoginByOauthNotAvailable = "api.user.login_by_oauth.not_available.app_error",
	UserLoginByOauthParse = "api.user.login_by_oauth.parse.app_error",
	UserLoginInactive = "api.user.login.inactive.app_error",
	UserLoginLdapNotAvailable = "api.user.login_ldap.not_available.app_error",
	UserLoginNotVerified = "api.user.login.not_verified.app_error",
	UserLoginUseAuthService = "api.user.login.use_auth_service.app_error",
	UserLoginWithDesktopTokenNotOauthOrSamlUser = "api.user.login_with_desktop_token.not_oauth_or_saml_user.app_error",
	UserOauthToEmailContext = "api.user.oauth_to_email.context.app_error",
	UserOauthToEmailMagicLink = "api.user.oauth_to_email.magic_link.app_error",
	UserOauthToEmailNotAvailable = "api.user.oauth_to_email.not_available.app_error",
	UserPatchUserLoginProviderAttributeSet = "api.user.patch_user.login_provider_attribute_set.app_error",
	UserPromoteGuestToUserMagicLinkEnabled = "api.user.promote_guest_to_user.magic_link_enabled.app_error",
	UserPromoteGuestToUserNoGuest = "api.user.promote_guest_to_user.no_guest.app_error",
	UserResetPasswordBrokenToken = "api.user.reset_password.broken_token.app_error",
	UserResetPasswordFailedAttemptsLdapAndEmailOnly = "api.user.reset_password_failed_attempts.ldap_and_email_only.app_error",
	UserResetPasswordFailedAttemptsPermissions = "api.user.reset_password_failed_attempts.permissions.app_error",
	UserResetPasswordInvalidLink = "api.user.reset_password.invalid_link.app_error",
	UserResetPasswordLinkExpired = "api.user.reset_password.link_expired.app_error",
	UserResetPasswordSso = "api.user.reset_password.sso.app_error",
	UserSamlNotAvailable = "api.user.saml.not_available.app_error",
	UserSendPasswordResetGuestMagicLink = "api.user.send_password_reset.guest_magic_link.app_error",
	UserSendPasswordResetSend = "api.user.send_password_reset.send.app_error",
	UserSendPasswordResetSso = "api.user.send_password_reset.sso.app_error",
	UserUpdateActiveCannotEnableGuestWhenGuestFeatureIsDisabled = "api.user.update_active.cannot_enable_guest_when_guest_feature_is_disabled.app_error",
	UserUpdateActiveCannotModifyStatusWhenUserIsManagedByLdap = "api.user.update_active.cannot_modify_status_when_user_is_managed_by_ldap.app_error",
	UserUpdateActiveNotEnable = "api.user.update_active.not_enable.app_error",
	UserUpdateActivePermissions = "api.user.update_active.permissions.app_error",
	UserUpdateOauthUserAttrsGetUser = "api.user.update_oauth_user_attrs.get_user.app_error",
	UserUpdatePasswordContext = "api.user.update_password.context.app_error",
	UserUpdatePasswordFailed = "api.user.update_password.failed.app_error",
	UserUpdatePasswordIncorrect = "api.user.update_password.incorrect.app_error",
	UserUpdatePasswordMagicLink = "api.user.update_password.magic_link.app_error",
	UserUpdatePasswordOauth = "api.user.update_password.oauth.app_error",
	UserUpdatePasswordPasswordHash = "api.user.update_password.password_hash.app_error",
	UserUpdatePasswordUserAndHashed = "api.user.update_password.user_and_hashed.app_error",
	UserUpdatePasswordValidAccount = "api.user.update_password.valid_account.app_error",
	UserUpdateUserAcceptedDomain = "api.user.update_user.accepted_domain.app_error",
	UserUpdateUserAcceptedGuestDomain = "api.user.update_user.accepted_guest_domain.app_error",
	UserUpdateUserLoginProviderAttributeSet = "api.user.update_user.login_provider_attribute_set.app_error",
	UserUpdateUserRolesLicense = "api.user.update_user_roles.license.app_error",
	UserUploadProfileUserArray = "api.user.upload_profile_user.array.app_error",
	UserUploadProfileUserCheckImageLimits = "api.user.upload_profile_user.check_image_limits.app_error",
	UserUploadProfileUserDecode = "api.user.upload_profile_user.decode.app_error",
	UserUploadProfileUserEncode = "api.user.upload_profile_user.encode.app_error",
	UserUploadProfileUserLoginProviderAttributeSet = "api.user.upload_profile_user.login_provider_attribute_set.app_error",
	UserUploadProfileUserNoFile = "api.user.upload_profile_user.no_file.app_error",
	UserUploadProfileUserOpen = "api.user.upload_profile_user.open.app_error",
	UserUploadProfileUserParse = "api.user.upload_profile_user.parse.app_error",
	UserUploadProfileUserStorage = "api.user.upload_profile_user.storage.app_error",
	UserUploadProfileUserTooLarge = "api.user.upload_profile_user.too_large.app_error",
	UserUploadProfileUserUploadProfile = "api.user.upload_profile_user.upload_profile.app_error",
	UserVerifyEmailBadLink = "api.user.verify_email.bad_link.app_error",
	UserVerifyEmailBrokenToken = "api.user.verify_email.broken_token.app_error",
	UserVerifyEmailLinkExpired = "api.user.verify_email.link_expired.app_error",
	WebhookCreateOutgoingIntersect = "api.webhook.create_outgoing.intersect.app_error",
	WebhookCreateOutgoingNotOpen = "api.webhook.create_outgoing.not_open.app_error",
	WebhookCreateOutgoingPermissions = "api.webhook.create_outgoing.permissions.app_error",
	WebhookCreateOutgoingTriggers = "api.webhook.create_outgoing.triggers.app_error",
	WebhookTeamMismatch = "api.webhook.team_mismatch.app_error",
	WebhookUpdateOutgoingIntersect = "api.webhook.update_outgoing.intersect.app_error",
	WebsocketHandlerInvalidParam = "api.websocket_handler.invalid_param.app_error",
	WebsocketHandlerServerBusy = "api.websocket_handler.server_busy.app_error",
	WebSocketConnectUpgrade = "api.web_socket.connect.upgrade.app_error",
	WebSocketRouterBadAction = "api.web_socket_router.bad_action.app_error",
	WebSocketRouterBadSeq = "api.web_socket_router.bad_seq.app_error",
	WebSocketRouterNotAuthenticated = "api.web_socket_router.not_authenticated.app_error",
	WebSocketRouterNoAction = "api.web_socket_router.no_action.app_error"
}
